[package]
name = "geodist"
version = "0.2.0"
edition = "2021"

[dependencies]
gdal = { version = "0.14", features = ["bindgen"] }
rand = "0.7"
serde_json = "1.0.89"
clap = { version = "4.0.32", features = ["derive"] }
